Vagrant.configure("2") do |config|

    config.vm.box = "debian/bullseye64"

    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.synced_folder File.expand_path("../../synced_folder", __FILE__), "/vagrant_shared", create: true

    config.vm.define "server" do |server|
        server.vm.hostname = "server.domain.local"
        server.vm.network "private_network", ip: "192.168.10.2"

        server.vm.provider "virtualbox" do |vb|
            vb.memory = "2048"
            vb.cpus = 2
        end

        server.vm.provision "shell", path: "install_puppetserver.sh"
    end

    config.vm.define "nodo01" do |nodo01|
        nodo01.vm.hostname = "nodo01.domain.local"
        nodo01.vm.network "private_network", ip: "192.168.10.3"
        nodo01.vm.network "forwarded_port", guest: 80, host: 8080

        nodo01.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 2
        end

        nodo01.vm.provision "shell", path: "install_puppetclient.sh"
    end
  end
  